export const tractors = [
  {
    name: "IMT 539.2 kabina",
    img: "/products/IMT 539.2 DI 2WD kabina.png",
    serija: "standardni",
    Snaga: "47, EUII",
    Pogon: "2WD",
    Auspuh: "Vertikalni",
    Filter: "Mokar",
    Kvacilo: "Dvostruko",
    Menjac: "8N+2R pomerljivi zupčanici, centralni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Direktan pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "1100",
    Upravljanje: "Ručno",
    PrednjeGume: "6.00 x 16",
    ZadnjeGume: "12.4 x 28",
    Kocnice: "Doboš",
    ROPS: "Opciono",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Da",
    RazvodniVentil: "/",
    Kompresor: "Da",
  },
  {
    name: "IMT 539.2 ROPS",
    img: "/products/IMT 539.2 DI 2WD ROPS.png",
    serija: "standardni",
    Snaga: "47, EUII",
    Pogon: "2WD",
    Auspuh: "Vertikalni",
    Filter: "Mokar",
    Kvacilo: "Dvostruko",
    Menjac: "8N+2R pomerljivi zupčanici, centralni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Direktan pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "1100",
    Upravljanje: "Ručno",
    PrednjeGume: "6.00 x 16",
    ZadnjeGume: "12.4 x 28",
    Kocnice: "Doboš",
    ROPS: "Opciono",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Da",
    RazvodniVentil: "/",
    Kompresor: "Da",
  },
  {
    name: "IMT 549.3 kabina",
    img: "/products/IMT 549.3 DI 4WD kabina.png",
    serija: "standardni",
    Snaga: "47, EUIII A",
    Pogon: "4WD",
    Auspuh: "Vertikalni",
    Filter: "Suvo",
    Kvacilo: "Dvostruko",
    Menjac: "8N+2R pomerljivi zupčanici, centralni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Direktan pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "1700",
    Upravljanje: "Hidraulički",
    PrednjeGume: "10.5/80 x 18",
    ZadnjeGume: "13.6 x 28",
    Kocnice: "Potopljene u ulju",
    ROPS: "Opciono",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Ne",
    RazvodniVentil: "Dva para hidrauličkih spojnica",
    Kompresor: "Da",
  },
  {
    name: "IMT 549.3 ROPS",
    img: "/products/IMT 549.3 DI 4WD ROPS.png",
    serija: "standardni",
    Snaga: "47, EUIII A",
    Pogon: "4WD",
    Auspuh: "Vertikalni",
    Filter: "Suvo",
    Kvacilo: "Dvostruko",
    Menjac: "8N+2R pomerljivi zupčanici, centralni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Direktan pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "1700",
    Upravljanje: "Hidraulički",
    PrednjeGume: "10.5/80 x 18",
    ZadnjeGume: "13.6 x 28",
    Kocnice: "Potopljene u ulju",
    ROPS: "Opciono",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Ne",
    RazvodniVentil: "Dva para hidrauličkih spojnica",
    Kompresor: "Da",
  },
  {
    name: "IMT 565.2 kabina",
    img: "/products/IMT 565.2 DI 4WD kabina.png",
    serija: "standardni",
    Snaga: "63, EUII",
    Pogon: "4WD",
    Auspuh: "Vertikalni",
    Filter: "Suvo",
    Kvacilo: "Dvostruko",
    Menjac: "8N+2R pomerljivi zupčanici, centralni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Planetarni pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "2050",
    Upravljanje: "Hidrostatičko",
    PrednjeGume: "9.5 x 24",
    ZadnjeGume: "16.9 x 28",
    Kocnice: "Potopljene u ulju",
    ROPS: "Opciono",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Ne",
    RazvodniVentil: "Dva para hidrauličkih spojnica",
    Kompresor: "Da",
  },
  {
    name: "IMT 565.2 ROPS",
    img: "/products/IMT 565.2 DI 4WD ROPS.png",
    serija: "standardni",
    Snaga: "63, EUII",
    Pogon: "4WD",
    Auspuh: "Vertikalni",
    Filter: "Suvo",
    Kvacilo: "Dvostruko",
    Menjac: "8N+2R pomerljivi zupčanici, centralni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Planetarni pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "2050",
    Upravljanje: "Hidrostatičko",
    PrednjeGume: "9.5 x 24",
    ZadnjeGume: "16.9 x 28",
    Kocnice: "Potopljene u ulju",
    ROPS: "Opciono",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Ne",
    RazvodniVentil: "Dva para hidrauličkih spojnica",
    Kompresor: "Da",
  },
  {
    name: "TAFE 4615 ROPS",
    img: "/products/TAFE 4615 4WD ROPS.png",
    serija: "standardni",
    Snaga: "47, EUIII A",
    Pogon: "4WD",
    Auspuh: "Vertikalni",
    Filter: "Suvo",
    Kvacilo: "Dvostruko",
    Menjac: "8N+2R pomerljivi zupčanici, bočni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Direktan pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "1450",
    Upravljanje: "Hidraulički",
    PrednjeGume: "8.3 x 24",
    ZadnjeGume: "13.6 x 28",
    Kocnice: "Potopljene u ulju",
    ROPS: "Da",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Ne",
    RazvodniVentil: "Dva para hidrauličkih spojnica",
    Kompresor: "Da",
  },
  {
    name: "TAFE 6515 ROPS",
    img: "/products/TAFE 6515 4WD ROPS.png",
    serija: "standardni",
    Snaga: "65, EUIII A",
    Pogon: "4WD",
    Auspuh: "Horizontalni",
    Filter: "Suvo",
    Kvacilo: "Jednostepeno",
    Menjac: "12+4 pomerljivi zupčanici, centralni položaj komande",
    PTO: "540 o/min",
    ZadnjaOsovina: "Planetarni pogon",
    Hidraulika: "Potopljena u ulje",
    KapacitetPodizanja: "2050",
    Upravljanje: "Hidraulički",
    PrednjeGume: "280 / 70 R18",
    ZadnjeGume: "380 / 70 R24",
    Kocnice: "Potopljene u ulju",
    ROPS: "Da",
    KlatecaPoteznica: "Da",
    PrednjiTegovi: "Ne",
    ZadnjiTegovi: "Ne",
    CevZaKipovanje: "Ne",
    RazvodniVentil: "Dva para hidrauličkih spojnica",
    Kompresor: "Ne",
  },
];
